-   id: gometaliner
    name: gometalinter
    entry: gometalinter --config=./.gometalinter.json --disable=gotype --disable=vet --disable=vetshadow
    description: Runs a group of go linters. Requires https://github.com/alecthomas/gometalinter.
    language: system
    files: '\.go'
